### ISSUE TITLE
Add python-lsp-ruff to docs

### ISSUE THREAD

**Issue by contang0** [asiloisad/pulsar-linter-ruff#1]
Thank you for this package! 

Just one thing that I think should be added to docs and mentioned in the extension itself: python-lsp-ruff seems to be a required dependency. Without it the linter was not showing any results from ruff.

https://github.com/python-lsp/python-lsp-ruff

**Comment by emendir** [comment]
The python `ruff`, which is mentioned as a requirement in the readme file (`pip install ruff`) suffices for pulsar-linter-ruff to work.

When installing the python package `python-lsp-ruff` (python-lsp-ruff) (which depends on `ruff`), pulsar's built-in [linter](https://web.pulsar-edit.dev/packages/linter) package kicks in and lints using ruff too, even if pulsar-linter-ruff is disabled.
I have just disabled pulsar-linter-ruff, because it requires the user to manually specify the severity levels of the different ruff rules, of which there are hundreds.
`python-lsp-ruff` and pulsar's built-in linter do this automatically.

**Comment by asiloisad** [comment]
It's strange that I have not found this issue earlier 🙁 emedit is correct. The only python package needed is just a `ruff`. A manually assign of each rule to severity class is a pain-in-ass, but I cannot find any clue from ruff docs how to assign them automaticly.
